# Generated by Django 5.2 on 2025-05-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='score',
            field=models.IntegerField(),
        ),
    ]
